config/routes.rb
Caramel::Application.routes.draw do
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get 'calendars/week' => 'calendars#index_week', :as => :calendars_week
  get "schedules/week" => "schedules#index_week", :as => :schedules_week
  get "rosters/add" => "rosters#add_student"
  delete "rosters/remove" => "rosters#remove_student"

  get 'lunchpads/api' => 'lunchpads#api'
  post 'lunchpads/lunch' => 'lunchpads#lunch'

  # destroy multi entries using checkboxes
  post 'programs/destroy_multi' => 'programs#destroy_multi'
  post 'teachers/destroy_multi' => 'teachers#destroy_multi'
  post 'staffs/destroy_multi' => 'staffs#destroy_multi'
  post 'students/destroy_multi' => 'students#destroy_multi'
  post 'regions/destroy_multi' => 'regions#destroy_multi'
  post 'instruments/destroy_multi' => 'instruments#destroy_multi'
  post 'program_types/destroy_multi' => 'program_types#destroy_multi'
  post 'schools/destroy_multi' => 'schools#destroy_multi'

  resources :events, :month_events, :calendars, :attendances, :navs, :lunchpads, :courses, :rosters, :password_resets, :schedules, :users, :staffs, :teachers, :regions, :programs, :instruments, :students, :admins, :program_types, :schools, :reports
	root 'session_page#signin'

  get 'session_page/signin' => 'session_page#signin', :as => :signin
  post 'session_page/verify' => 'session_page#verify'
  get 'session_page/signout' => 'session_page#signout'

  # teachers of a program
  # instruments of a program  
  resources :programs do
    resources :teachers
    resources :instruments
  end

  # programs of a teacher  
  resources :teachers do
    resources :programs
  end

  # regions of a teacher  
  resources :teachers do
    resources :regions
  end

end

app/controllers/session_page_controller.rb
class SessionPageController < ApplicationController
  def signin
		render :layout => false
  end

  def signout
		logout
		redirect_to root_url
  end

	def verify
		user = login(params[:email], params[:password], params[:remember_me])
    if user
      if user.type == 'Admin'
        redirect_to '/staffs'
      elsif user.type == 'Staff'
        redirect_to '/teachers'
      elsif user.type == 'Teacher'
        redirect_to '/students'
      end
    else
			redirect_to root_url
    end
	end
end

app/views/session_page/_forgot_password_form.html.haml
= simple_form_for :user, :url => "/password_resets", :method => :post do |f|
  = f.input :email
  = f.button :submit, "Reset my password!"
-# = form_tag password_resets_path, :method => :post do
-#   .field
-#     = label_tag :email
-#     = text_field_tag :email
-#     = submit_tag "Reset my password!"

app/views/session_page/signin.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title Sign in
    = stylesheet_link_tag :session_page, :media => "all"
    = favicon_link_tag
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container{:style => 'margin-left: 10px; width: 100%;'}
          %a.brand{:href => "#"}
            Music Kids
    .content#login-content
      = form_tag '/session_page/verify', method: 'post' do
        %fieldset
          %legend{:style => 'border-bottom-width: 1px; border-color: #aaa;'}
            %strong
              Sign in
          %label
            %strong
              Email
          = text_field_tag :email, nil, :placeholder => 'Email', :class => 'login-input'
          %label
            %strong
              Password
          = password_field_tag :password, nil, :placeholder => 'Password', :class => 'login-input'
          .form-inline
            %label.checkbox
              = check_box_tag :remember_me
              remember me
            #login-sign-in
              = submit_tag "Sign in", :class => 'btn'
      -#   %fieldset
      -#     %legend
      -#       %strong
      -#         Forgot Password?
      -# = render 'forgot_password_form'