config/routes.rb
Caramel::Application.routes.draw do
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get 'calendars/week' => 'calendars#index_week', :as => :calendars_week
  get "schedules/week" => "schedules#index_week", :as => :schedules_week
  get "rosters/add" => "rosters#add_student"
  delete "rosters/remove" => "rosters#remove_student"

  get 'lunchpads/api' => 'lunchpads#api'
  post 'lunchpads/lunch' => 'lunchpads#lunch'

  # destroy multi entries using checkboxes
  post 'programs/destroy_multi' => 'programs#destroy_multi'
  post 'teachers/destroy_multi' => 'teachers#destroy_multi'
  post 'staffs/destroy_multi' => 'staffs#destroy_multi'
  post 'students/destroy_multi' => 'students#destroy_multi'
  post 'regions/destroy_multi' => 'regions#destroy_multi'
  post 'instruments/destroy_multi' => 'instruments#destroy_multi'
  post 'program_types/destroy_multi' => 'program_types#destroy_multi'
  post 'schools/destroy_multi' => 'schools#destroy_multi'

  resources :events, :month_events, :calendars, :attendances, :navs, :lunchpads, :courses, :rosters, :password_resets, :schedules, :users, :staffs, :teachers, :regions, :programs, :instruments, :students, :admins, :program_types, :schools, :reports
	root 'session_page#signin'

  get 'session_page/signin' => 'session_page#signin', :as => :signin
  post 'session_page/verify' => 'session_page#verify'
  get 'session_page/signout' => 'session_page#signout'

  # teachers of a program
  # instruments of a program  
  resources :programs do
    resources :teachers
    resources :instruments
  end

  # programs of a teacher  
  resources :teachers do
    resources :programs
  end

  # regions of a teacher  
  resources :teachers do
    resources :regions
  end

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :course
  validates :start_time, :end_time, :date, :presence => true
  validate :events_cannot_overlap, :courses_must_in_term, :events_must_in_available_time_slots, :start_time_cannot_after_end_time
  # validate :no_more_one_schedule_on_one_day
  attr_accessor :recurring, :name, :course_type
  def group
    course.course_type == "GroupCourse"
  end
  
  def save_recurring
    day_of_week = date.wday
    days = Term.find(course.program.term_id).recurring_days(day_of_week, :start_date => date)
    puts days
    r = true
    days.each do |day|
      r = Schedule.new(:date => day, :start_time => start_time, :end_time => end_time, :course_id => course_id).save && r
    end
    # r
  end
  def update_recurring(schedule_params, recurring_type)
    if recurring_type == "all"
      recurring_schedules = Schedule.where(:course_id => course_id)  
    elsif recurring_type == "future"
      recurring_schedules = Schedule.where("course_id = ? AND date >= ? AND start_time >= ?", course_id, date, start_time)
    end
    recurring_schedules.each do |e|
      e.update_attributes(schedule_params)
    end
  end
  def destroy_recurring(recurring_type)
    if recurring_type == "all"
      recurring_schedules = Schedule.where(:course_id => course_id)
    elsif recurring_type == "future"
      recurring_schedules = Schedule.where("course_id = ? AND date >= ? AND start_time >= ?", course_id, date, start_time)
    end
    recurring_schedules.each do |e|
      e.destroy
    end
  end
  private
  def no_more_one_schedule_on_one_day
    if Schedule.where(:course_id => course_id, :date => date).count > 0
      errors.add(:base, "class can only be scheduled once on one day")
    end
  end
  def events_must_in_available_time_slots
    return unless start_time and end_time
    available = false
    term_id = course.program.term_id
    school_id = course.program.school_id
    dummy_start_time = Time.gm(2000, 1, 1, start_time.hour, start_time.min, start_time.sec)
    dummy_end_time = Time.gm(2000, 1, 1, end_time.hour, end_time.min, end_time.sec)
    
    
    calendars = Calendar.where(:date => date, :school_id => school_id, :available => true)
    # calendars = Calendar.where(:date => date, :term_id => term_id, :school_id => school_id, :available => true)
    calendars.find_each do |cal|
      puts dummy_start_time
      puts dummy_end_time
      if cal[:start_time] <= dummy_start_time and dummy_end_time <= cal[:end_time]
        available = true
        break
      end
    end
    errors.add(:base, "must in available time slots") unless available
  end
  def courses_must_in_term
    term = course.program.term
    if course.course_type == "GroupCourse"
      unless term.start_date <= date and date <= term.end_date
        errors.add(:date, "must in term")
      end
    end
  end
  def events_cannot_overlap
    return unless start_time and end_time
    @dummy_start_time = Time.gm(2000, 1, 1, start_time.hour, start_time.min, start_time.sec)
    @dummy_end_time = Time.gm(2000, 1, 1, end_time.hour, end_time.min, end_time.sec)
    program_id = course.program_id

    Schedule.where(:date => date).joins(:course => :program).where({:courses => {:program_id => program_id}}).find_each do |event|
      if event.id != id and overlap?(event)
        errors.add(:base, "time conflicts with schedule #{event.id}")
        return
      end
    end
  end
  def start_time_cannot_after_end_time
    if start_time >= end_time
      errors.add(:base, "end time must after start time")
    end
  end
  def overlap?(event)
    if date == event.date and @dummy_end_time > event.start_time and @dummy_start_time < event.end_time
      true
    else
      false
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_filter :require_login
  def index
    @programs = case current_user[:type]
                when "Teacher"
                  Teacher.find(current_user[:id]).programs.includes(:school).order("school_id ASC")
                when "Staff"
                  Staff.find(current_user[:id]).programs.includes(:school).order("school_id ASC")
                when "Admin"
                  Program.all.includes(:school).order("school_id ASC")
                end
    @schools = @programs.map {|program| program.school}.uniq if @programs
    @school = @schools.try(:first)
    @program = @programs.try(:find_by, :id => params[:program_id]) || @programs.try(:first)
    @program_id = @program.try(:id)
    school_id = @school.try(:id)
    program_ids = @programs.map {|program| program.id}
    @schedules = rehash_objs(Schedule.joins(:course).where({:courses => {:program_id => program_ids}}))
    @calendars = rehash_objs(Calendar.where(:school_id => school_id))

    @month = (params[:month] || Date.today.month).to_i
    @year = (params[:year] || Date.today.year).to_i
    @first_month = 9
    @start_year = case @month < @first_month
                  when true
                    @year - 1
                  when false
                    @year
                  end
    @day = (params[:day] || Date.today.day).to_i
    @date = Date.new(@year, @month, @day)
    @today = Date.today
    # render :json => @calendars
  end
  def index_week
    @programs = case current_user[:type]
                when "Teacher"
                  Teacher.find(current_user[:id]).programs.includes(:school).order("school_id ASC")
                when "Staff"
                  Staff.find(current_user[:id]).programs.includes(:school).order("school_id ASC")
                when "Admin"
                  Program.all.includes(:school).order("school_id ASC")
                end

    @program = @programs.try(:find_by, :id => params[:program_id]) || @programs.try(:first)
    @program_id = @program.try(:id)
    program_ids = @programs.map {|program| program.id}
    @schools = @programs.map {|program| program.school}.uniq if @programs
    @school = @schools.try(:first)
    school_id = @school.try(:id)
    @schedules = rehash_objs(Schedule.joins(:course).where({:courses => {:program_id => program_ids}}))
    @calendars = rehash_objs(Calendar.where(:school_id => school_id))

    @month = (params[:month] || Date.today.month).to_i
    @year = (params[:year] || Date.today.year).to_i
    @day = (params[:day] || Date.today.day).to_i
    @date = Date.new(@year, @month, @day)
    @today = Date.today
  end
  def new
    @schedule = Schedule.new
    @date = params[:date]
    @program_id = params[:program_id]
    puts @program_id
    @courses = Course.where(:program_id => params[:program_id])
    puts @courses
    render :layout => false
  end
  def create
    unless params[:schedule][:name].empty?
      course = Course.new(:program_id => params[:schedule][:program_id], :name => params[:schedule][:name], :course_type => params[:schedule][:course_type])
      course_saved = course.save
      if course_saved
        course_id = course.id
        @schedule = Schedule.new(schedule_params)
        @schedule.course_id = course_id
        # @schedule = Schedule.new({:course_id => course_id, :start_time => params[:schedule][:start_time], :end_time => params[:schedule][:end_time], :date => params[:schedule][:date]})
        r = if params[:schedule][:course_type] == "RegularCourse"
          @schedule.save_recurring
        else
          @schedule.save
        end
        if r
          redirect_to schedules_path
        else
          render :new, :status => :unprocessable_entity, :layout => false
        end
      else
        render :new, :status => :unprocessable_entity, :layout => false
      end
    else
      course_id = params[:schedule][:course_id]
      @schedule = Schedule.new(schedule_params)
      r = if Course.find(course_id).course_type == "RegularCourse"
        @schedule.save_recurring
      else
        @schedule.save
      end
      if r
        redirect_to schedules_path
      else
        render :new, :status => :unprocessable_entity, :layout => false
      end
    end
  end
  def edit
    @schedule = Schedule.find(params[:id])
    render :layout => false
  end
  def update
    @schedule = Schedule.find(params[:id])
    params[:schedule].delete("date")
    
    r = if Course.find(params[:schedule][:course_id]).course_type == "RegularCourse" and (params[:schedule][:recurring] == "all" or params[:schedule][:recurring] == "future")
      @schedule.update_recurring(schedule_params, params[:schedule][:recurring])
    else
      @schedule.update_attributes(schedule_params)
    end
    if r
      render :text => "success"
    else
      render :edit, :status => :unprocessable_entity, :layout => false
    end
  end
  def destroy
    schedule = Schedule.find(params[:id])
    if Course.find(schedule.course_id).course_type = "RegularCourse" and (params[:recurring] == "all" or params[:recurring] == "future")
      schedule.destroy_recurring(params[:recurring])
    else
      schedule.destroy
    end
    render :text => "delete success"
  end
  private
  # def rehash_cal_objs(objs)
  #   r = {}
  #   for obj in objs
  #     unless r.has_key? obj[:date]
  #       r[obj[:date]] = []
  #     end
  #     r[obj[:date]] << obj
  #   end
  #   r
  # end
  def rehash_cal_objs(objs)
    r = {}
    for obj in objs
     
      r[obj[:date]] = [] unless r.has_key? obj[:date]
      
      r[obj[:day_of_week]] = {} unless r.has_key? obj[:day_of_week]
     
      r[obj[:day_of_week]][obj[:date]] = [] unless r[obj[:day_of_week]].has_key? obj[:date]

      r[obj[:date]] << obj
      r[obj[:day_of_week]][obj[:date]] << obj

    end
    r
  end
  def rehash_objs(objs)
    r = {}
    for obj in objs
      r[obj[:date]] = [] unless r.has_key? obj[:date]
      r[obj[:date]] << obj
    end
    r
  end
  # def rehash_objs(objs)
  #   r = {}
  #   for obj in objs
  #     if obj.course[:course_type] == "GroupCourse"
  #       r[obj[:date]] = [] unless r.has_key? obj[:date]
  #       r[obj[:date]] << obj
  #     else
  #       r[obj[:day_of_week]] = [] unless r.has_key? obj[:day_of_week]
  #       r[obj[:day_of_week]] << obj
  #     end
  #   end
  #   r
  # end
  def schedule_params
    params.require(:schedule).permit(:date, :start_time, :end_time, :day_of_week, :course_type, :course_id, :name)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form_edit.html.haml
#schedule-form-body
  = simple_form_for @schedule do |f|
    = f.error_notification
    = display_base_errors @schedule
    = f.association :course, :collection => @courses, :label_method => :name, :value_method => :id, :include_blank => false, :wrapper_html => {:id => "schedule-course-select"}
    = f.input :name, :wrapper_html => {:id => "schedule-course-name"}
    = f.input :course_type, :collection => [["Regular", "RegularCourse"], ["Group", "GroupCourse"]], :include_blank => false, :wrapper_html => {:id => "schedule-course-type"}
    = f.input :start_time, :start_hour => 6, :end_hour => 18, :ampm => true
    = f.input :end_time, :start_hour => 6, :end_hour => 18, :ampm => true
    = f.input :date, :input_html => {:value => @date ? Date.strptime(@date) : Date.today}, :as => :hidden
    = f.input :program_id, :input_html => {:value => @program_id}, :as => :hidden
    = f.input :recurring, :collection => [["None","none"], ["Future", "future"], ["All", "all"]], :include_blank => false, :wrapper_html => {:id => "schedule-recurring-selection"}
    = f.input :term_id, :input_html => {:value => params[:term_id]}, :as => :hidden
    -# = f.collection_radio_buttons :recurring, [[1, "None"], [2, "Apply to future events"], [3, "Apply to all events"]], :first, :last, :input_html => {:value => 1}
    -# = f.button :submit

-#XXX Use javascript to hide the submit button, but reappear if error occurs during the submission

app/views/schedules/_form_new.html.haml
#schedule-form-body
  = simple_form_for @schedule do |f|
    = f.error_notification
    = display_base_errors @schedule
    = f.association :course, :collection => @courses, :label_method => :name, :value_method => :id, :include_blank => false, :wrapper_html => {:id => "schedule-course-select"}
    = f.input :name, :wrapper_html => {:id => "schedule-course-name"}
    = f.input :course_type, :collection => [["Regular", "RegularCourse"], ["Group", "GroupCourse"]], :include_blank => false, :wrapper_html => {:id => "schedule-course-type"}
    = f.input :start_time, :start_hour => 6, :end_hour => 18, :ampm => true
    = f.input :end_time, :start_hour => 6, :end_hour => 18, :ampm => true
    = f.input :date, :input_html => {:value => @date ? Date.strptime(@date) : Date.today}, :as => :hidden
    = f.input :program_id, :input_html => {:value => @program_id}, :as => :hidden
    = f.input :term_id, :input_html => {:value => params[:term_id]}, :as => :hidden
    -# = f.collection_radio_buttons :recurring, [[1, "None"], [2, "Apply to future events"], [3, "Apply to all events"]], :first, :last, :input_html => {:value => 1}
    -# = f.button :submit

-#XXX Use javascript to hide the submit button, but reappear if error occurs during the submission

app/views/schedules/_form_old.html.haml
#schedule-form-body
  = simple_form_for @schedule do |f|
    = f.association :course, :collection => @course, :label_method => :name, :value_method => :id, :include_blank => false
    = f.input :start_time, :start_hour => 8, :end_hour => 16, :ampm => true
    = f.input :end_time, :start_hour => 8, :end_hour => 16, :ampm => true
    -# = f.input :day_of_week, :collection => [["Sunday", 0], ["Monday", 1], ["Tuesday", 2], ["Wednesday", 3], ["Thursday", 4], ["Friday", 5], ["Saturday", 6]], :include_blank => false, :selected => @date ? Date.parse(@date).wday : Date.today.wday, :input_html => {:style => "display: none"}, :label => false
    = f.input :date, :input_html => {:value => @date ? Date.strptime(@date) : Date.today}, :as => :hidden
    -# = f.input :recurring, :as => :boolean
    -# = f.button :submit

-#XXX Use javascript to hide the submit button, but reappear if error occurs during the submission

app/views/schedules/_schedule_events.html.haml
- if @calendars.has_key? day
  - for event in @calendars[day]
    - style = event_style(event[:start_time], event[:end_time], start_hour, slot_height, slots_per_hour)
    - klass = "wc-cal-background-event schedule-cal"
    - klass << if event.available then " available" else " unavailable" end
    %div{:class => klass, :style => style, :data => {:eventid => event.id}}
      .wc-time.ui-corner-all
        = "#{event.start_time.strftime("%I:%M %P")}-#{event.end_time.strftime("%I:%M %P")}"
- if @schedules.has_key? day
  - for event in @schedules[day]
    - style = event_style(event[:start_time], event[:end_time], start_hour, slot_height, slots_per_hour)
    - klass = "wc-cal-event schedule-cal"
    - klass << if event.course.course_type == "RegularCourse" then " regular-class" else " group-class" end
    %div{:class => klass, :style => style, :data => {:eventid => event.id}}
      .wc-time.ui-corner-all
        = "#{event.start_time.strftime("%I:%M %P")}-#{event.end_time.strftime("%I:%M %P")}"
      .wc-title
        = event.course.name

app/views/schedules/_schedule_grid.html.haml
- klass = "day-text"
- if day.month != month
  - klass << " not-current-month"
- else
  - klass << " today" if day == @today
  - if @calendars.has_key? day
    - klass << " schedule-holiday" if day_marking(@calendars[day]) == "unavailable"
  - if @schedules.has_key? day
    - klass << " schedule-day" unless @schedules[day].empty?
%td{:data => {:year => day.year, :month => day.month, :day => day.day}, :class => klass}
  = link_to day.day, self.send(base_path, :year => day.year, :month => day.month, :day => day.day, :program_id => @program_id), :class => "day-link"

app/views/schedules/_schedule_nav_filter.html.haml
= nav_filter_for "school", @schools, :base_url => "/schedules", :year => params[:year], :month => params[:month], :day => params[:day], :default_text => "#{@school.name}"
%li{:class => "#{active == 'week' ? 'active' : ''}"}
  = link_to "week", schedules_week_path(:program_id => @program_id), :id => "subnav-week"
%li{:class => "#{active == 'year' ? 'active' : ''}"}
  = link_to "year", schedules_path(:program_id => @program_id), :id => "subnav-year"

app/views/schedules/_schedule_week_nav_filter.html.haml
= nav_filter_for "school", @schools, :base_url => "/schedules/week", :year => params[:year], :month => params[:month], :day => params[:day], :default_text => "#{@school.name}"
%li{:class => "#{active == 'week' ? 'active' : ''}"}
  = link_to "week", schedules_week_path(:program_id => @program_id), :id => "subnav-week"
%li{:class => "#{active == 'year' ? 'active' : ''}"}
  = link_to "year", schedules_path(:program_id => @program_id), :id => "subnav-year"

app/views/schedules/_week_nav_pills.html.haml
%li
  = link_to "Today", self.send(base_path, :year => @today.year, :month => @today.month, :day => @today.day, :school_id => @school_id, :program_id => @program_id)
%li
  = link_to "<", self.send(base_path, :year => @date.prev_week.year, :month => @date.prev_week.month, :day => @date.prev_week.day, :school_id => @school_id, :program_id => @program_id)
%li
  = link_to ">", self.send(base_path, :year => @date.next_week.year, :month => @date.next_week.month, :day => @date.next_week.day, :school_id => @school_id, :program_id => @program_id)
%li
  %span.navbar-text#subnav-text
    = @date.beginning_of_week(:sunday).strftime("%B %-d, %Y") + " - " + @date.end_of_week(:sunday).strftime("%B %-d, %Y")

app/views/schedules/_year_nav_pills.html.haml
%li
  = link_to "Today", self.send(base_path, :year => @today.year, :school_id => @school_id, :program_id => @program_id)
%li
  = link_to "<", self.send(base_path, :year => @year - 1, :school_id => @school_id, :program_id => @program_id)
%li
  = link_to ">", self.send(base_path, :year => @year + 1, :school_id => @school_id, :program_id => @program_id)
%li
  %span.navbar-text#subnav-text
    = "#{@start_year} - #{@start_year + 1}"

app/views/schedules/edit.html.haml
= render "form_edit"

app/views/schedules/index.html.haml
- content_for :title do
  schedule
- content_for :sidemenu do
  - render '/layouts/classes_page_sidebar'
- if @program
  - content_for :subnav do
    = render "/layouts/subnav", :nav_pills_partial => "/schedules/year_nav_pills", :nav_filter_partial => "/schedules/schedule_nav_filter", :active => "year", :base_path => :schedules_path
  - content_for :main do
    = render "/layouts/calendars/annual_calendar", :base_path => :schedules_week_path, :grid_partial => "/schedules/schedule_grid"
- else
  - content_for :main do
    = render "/layouts/empty_program_page"

app/views/schedules/index_week.html.haml
- content_for :title do
  schedule 
- content_for :sidemenu do
  - render '/layouts/classes_page_sidebar'
- if @schedules
  - content_for :subnav do
    = render "/layouts/subnav", :active => "week", :nav_pills_partial => "/schedules/week_nav_pills", :nav_filter_partial => "/schedules/schedule_week_nav_filter", :base_path => :schedules_week_path
  - content_for :main do
    = render "/layouts/calendars/weekly_calendar", :calendar_name => "schedule", :event_partial => "/schedules/schedule_events"
    -# = weekly_calendar_for @schedules, :year => @year.to_i, :month => @month.to_i, :day => @day.to_i, :category_method => :group, :calendar_name => "course", :program => @program, :background_calendar => @calendars do |c|
    -#   = c.draw_weekly_calendar_nav
    -#   = c.draw_weekly_calendar_body

    = modal_for "schedule", :delete_button => true
- else
  - content_for :main do
    = render "/layouts/empty_program_page"

app/views/schedules/new.html.haml
= render "form_new"